---
title: "cross_validation"
author: "Dantong Zhu"
date: "2021/12/3"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(mgcv)
```

## Simulate Data

```{r}
nonlin_df = 
  tibble(
    id = 1:100,
    x = runif(100, 0, 1),
    y = 1 - 10 * (x - .3)^2 + rnorm(100, 0, .3)
  )
```
 
 Look at the data
 
```{r}
nonlin_df %>% 
  ggplot(aes(x = x, y = y))+
  geom_point()
```
 
## Cross validation --  by hand

get a training and testing datasets
```{r}
train_df = sample_n(nonlin_df, size = 80)
test_df = anti_join(nonlin_df, train_df, by = "id")
```

fit three models

```{r}
linear_mod = lm(y ~ x, data = train_df)
smooth_mod = gam(y ~ s(x), data = train_df)
wiggly_mod = gam(y ~ s(x, k =30), sp = 10e-6, data = train_df) 
```

can I see what I just did...
```{r}
train_df %>% 
  add_predictions(wiggly_mod) %>% 
  ggplot(aes(x = x, y = y)) +
  geom_point() + 
  geom_line(aes(y = pred), color = "red")
```

```{r}
train_df %>% 
  gather_predictions(linear_mod,smooth_mod,wiggly_mod) %>% 
  ggplot(aes(x = x, y = y)) +
  geom_point() + 
  geom_line(aes(y = pred), color = "red")+
  facet_grid(. ~model)
```

look at the prediction accuracy.

```{r}
rmse(linear_mod,test_df)
rmse(smooth_mod,test_df)
rmse(wiggly_mod,test_df)
```

## Cross validation using 'modelr'
```{r}
cv_df = 
  crossv_mc(nonlin_df, 100)
```

what is happening here

```{r}
cv_df %>% 
  pull(train) %>% 
  .[[1]] %>% 
  as_tibble()

cv_df %>% 
  pull(test) %>% 
  .[[1]] %>% 
  as_tibble()
```

```{r}
cv_df = 
  cv_df %>%
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )
```

let's try to fit models and get RMSEs for them

```{r}
cv_df = 
  cv_df %>% 
  mutate(
    linear_mod = map(.x = train, ~lm(y ~ x, data = .x)),
    smooth_mod = map(.x = train, ~gam(y ~ s(x), data = .x)),
    wiggly_mod = map(.x = train, ~gam(y ~ s(x, k = 30), sp = 10e-6, data = .x))
  ) %>% 
  mutate(
    rmse_linear = map2_dbl(.x = linear_mod, .y = test, ~rmse(model = .x, data = .y)),
    rmse_smooth = map2_dbl(.x = smooth_mod, .y = test, ~rmse(model = .x, data = .y)),
    rmse_wiggly = map2_dbl(.x = wiggly_mod, .y = test, ~rmse(model = .x, data = .y))
  )
```

what do the results say about the model choices?
```{r}
cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model",
    values_to = "rmse",
    names_prefix = "rmse_"
  ) %>% 
  group_by(model) %>% 
  summarise(avg_rmse = mean(rmse))
```



