---
title: "linear_models"
author: "Dantong Zhu"
date: "2021/12/2"
output: html_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(p8105.datasets)
```

```{r}
data("nyc_airbnb")
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighbourhood = neighbourhood
  ) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighbourhood, room_type)
```

## Fit a model

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = borough)) +
  geom_point()
```

let's fit the model we care about
```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

let's look at the result
```{r}
fit

summary(fit)
summary(fit)$coef
coef(fit)

```

let's look at the result better
```{r}
broom::glance(fit)

broom::tidy(fit) %>%
  select(-std.error, -statistic) %>%
  mutate(
    term == str_replace(term, "borough", "Borough: ")
  ) %>% 
  knitr::kable(digits = 3)
```

## Be in control 
```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type)
  )
```

look at that plot again
```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = borough)) +
  geom_point()
```

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
broom::tidy(fit)
broom::glance(fit)
```

## Diagnostics

```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = borough, y = resid))+
  geom_violin() +
  ylim(-500, 1500)

nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = stars, y = resid))+
           geom_point()+
           facet_wrap(. ~ borough)
```

## Hypothesis tests

This does t-test by default
```{r}
fit %>% 
  broom::tidy()
```

what about the significance of 'borough'
```{r}
fit_null = lm(price ~ stars, data = nyc_airbnb)
fit_alt = lm(price ~ stars + borough, data = nyc_airbnb)

anova(fit_null, fit_alt) %>% 
  broom::tidy()
```

## Nest data, fit models

```{r}
fit = lm(price ~ stars * borough + room_type*borough, data = nyc_airbnb)

broom::tidy(fit)
```

```{r}
nyc_airbnb %>% 
  nest(data = -borough) %>% 
  mutate(
     models = map(.x = data, ~lm(price ~ stars + room_type, data = .x)),
     results = map(models, broom::tidy)
  ) %>% 
  select(-data, -models) %>% 
  unnest(results) %>% 
  filter(term != "(Intercept)") %>% 
  select(borough, term, estimate) %>% 
  pivot_wider(
    names_from = borough,
    values_from = estimate
  )
```

let's nest even more

```{r}
nyc_airbnb %>% 
  filter(borough == "Manhattan") %>% 
  nest(data = -neighbourhood) %>% 
  mutate(
    models = map(.x = data, ~lm(price ~ stars + room_type, data = .x)),
    results = map(models, broom::tidy)
  ) %>% 
  select(-data, -models) %>% 
  unnest(results) %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighbourhood, y = estimate)) +
  geom_point()+
  facet_wrap(. ~ term)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
  
```


